name: Deploy Server

on:
  push:
    branches:
      - master
    paths:
      - "server/src/**"
  workflow_dispatch:

jobs:
  deploy:
    name: Run remote script
    runs-on: ubuntu-latest
    steps:
      - name: Connect & execute script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            ${{ secrets.SSH_SCRIPT }}
